### PR TITLE
New Feature and Improvements

### PR DESCRIPTION
**Pull request by ranocha**
I've added an option `constrain_emb_stability` to `rk_opt` to constraint the stability polynomial of embedded schemes. In some cases, this can help and improve the chance to find valid solutions. In other cases, this doesn't help. Nevertheless, I thought it might be nice to have this feature available in RK-Opt.

I've also tweaked some options (`TolCon`) and the output file name (including the class name) slightly.

### CODE REVIEW

**Comment by ketch** [comment]
The expectation is that you would do this using `polyopt` and the existing arguments `emb_poly_coeff_ind,emb_poly_coeff_val` to do this.  What's the motivation for adding this approach?

**Comment by ranocha** [comment]
Sometimes, `fmincon` cannot find solutions if `emb_poly_coeff_ind,emb_poly_coeff_val` are given. In these situations, there are a few parameter combinations where it can be advantageous to ask `fmincon` to directly constraint the value of the embedded stability function at a few points.

**Comment by ranocha** [comment]
If you don't like the new option `constrain_emb_stability`, I can also remove it. The other two commits could be considered separately.

**Comment by ketch** [comment]
>Sometimes, fmincon cannot find solutions if emb_poly_coeff_ind,emb_poly_coeff_val are given. In these situations, there are a few parameter combinations where it can be advantageous to ask fmincon to directly constraint the value of the embedded stability function at a few points.  In general, the existing approach using polyopt and emb_poly_coeff_ind,emb_poly_coeff_val seems to be better for most problems. 

That makes sense.  Just add this explanation, rather than the current one that says the option is "not useful" ;-).

**Comment by ranocha** [comment]
Yeah, you're right. Adding a new feature and describing it as "not useful" is probably not a good combination.

**Pull request merged**
